export const BlockType = {
  AIR:            0,
  GRASS:          1,
  DIRT:           2,
  STONE:          3,
  SAND:           4,
  WOOD:           5,
  LEAVES:         6,
  TALL_GRASS:     7,
  FLOWER_RED:     8,
  FLOWER_YEL:     9,
  SNOW:           10,
  CACTUS:         11,
  PLANKS:         12,
  COBBLESTONE:    13,
  GRAVEL:         14,
  GLASS:          15,
  BRICK:          16,
  BOOKSHELF:      17,
  CHEST:          18,
  CRAFTING_TABLE: 19,
  FURNACE:        20,
  COAL_ORE:       21,
  IRON_ORE:       22,
  GOLD_ORE:       23,
  DIAMOND_ORE:    24,
  OBSIDIAN:       25,
  ICE:            26,
  PUMPKIN:        27,
  HAY_BALE:       28,
  CLAY:           29,
  TNT:            30,
  GLOWSTONE:      31,
};

export const BlockColor = {
  [BlockType.GRASS]:          0x5a8f3c,
  [BlockType.DIRT]:           0x8b6340,
  [BlockType.STONE]:          0x808080,
  [BlockType.SAND]:           0xe2c47a,
  [BlockType.WOOD]:           0x6b4226,
  [BlockType.LEAVES]:         0x2d7a2d,
  [BlockType.TALL_GRASS]:     0x4ec840,
  [BlockType.FLOWER_RED]:     0xcc2222,
  [BlockType.FLOWER_YEL]:     0xf0d020,
  [BlockType.SNOW]:           0xeef4ff,
  [BlockType.CACTUS]:         0x2d7a1f,
  [BlockType.PLANKS]:         0xc8944a,
  [BlockType.COBBLESTONE]:    0x707070,
  [BlockType.GRAVEL]:         0x909090,
  [BlockType.GLASS]:          0xaaddff,
  [BlockType.BRICK]:          0x9e4a3a,
  [BlockType.BOOKSHELF]:      0xc0843c,
  [BlockType.CHEST]:          0xa06830,
  [BlockType.CRAFTING_TABLE]: 0xb07840,
  [BlockType.FURNACE]:        0x888888,
  [BlockType.COAL_ORE]:       0x505050,
  [BlockType.IRON_ORE]:       0xc09070,
  [BlockType.GOLD_ORE]:       0xe0c030,
  [BlockType.DIAMOND_ORE]:    0x30d8e8,
  [BlockType.OBSIDIAN]:       0x201828,
  [BlockType.ICE]:            0xaaddff,
  [BlockType.PUMPKIN]:        0xe06020,
  [BlockType.HAY_BALE]:       0xd4a820,
  [BlockType.CLAY]:           0x9ba8b4,
  [BlockType.TNT]:            0xcc2222,
  [BlockType.GLOWSTONE]:      0xffcc44,
};

export const BlockName = {
  [BlockType.AIR]:            'AIR',
  [BlockType.GRASS]:          'Herbe',
  [BlockType.DIRT]:           'Terre',
  [BlockType.STONE]:          'Pierre',
  [BlockType.SAND]:           'Sable',
  [BlockType.WOOD]:           'Bois',
  [BlockType.LEAVES]:         'Feuilles',
  [BlockType.TALL_GRASS]:     'Herbe haute',
  [BlockType.FLOWER_RED]:     'Fleur rouge',
  [BlockType.FLOWER_YEL]:     'Fleur jaune',
  [BlockType.SNOW]:           'Neige',
  [BlockType.CACTUS]:         'Cactus',
  [BlockType.PLANKS]:         'Planches',
  [BlockType.COBBLESTONE]:    'Cobblestone',
  [BlockType.GRAVEL]:         'Gravier',
  [BlockType.GLASS]:          'Verre',
  [BlockType.BRICK]:          'Briques',
  [BlockType.BOOKSHELF]:      'Biblioth\u00e8que',
  [BlockType.CHEST]:          'Coffre',
  [BlockType.CRAFTING_TABLE]: '\u00c9tabli',
  [BlockType.FURNACE]:        'Four',
  [BlockType.COAL_ORE]:       'Minerai de charbon',
  [BlockType.IRON_ORE]:       'Minerai de fer',
  [BlockType.GOLD_ORE]:       'Minerai d\'or',
  [BlockType.DIAMOND_ORE]:    'Minerai de diamant',
  [BlockType.OBSIDIAN]:       'Obsidienne',
  [BlockType.ICE]:            'Glace',
  [BlockType.PUMPKIN]:        'Citrouille',
  [BlockType.HAY_BALE]:       'Botte de foin',
  [BlockType.CLAY]:           'Argile',
  [BlockType.TNT]:            'TNT',
  [BlockType.GLOWSTONE]:      'Pierre lumineuse',
  [100]: 'Pomme',
  [101]: 'Pain',
};

export const PLACEABLE_BLOCKS = [
  BlockType.GRASS,
  BlockType.DIRT,
  BlockType.STONE,
  BlockType.SAND,
  BlockType.WOOD,
  BlockType.LEAVES,
  BlockType.PLANKS,
  BlockType.COBBLESTONE,
  BlockType.GRAVEL,
  BlockType.GLASS,
  BlockType.BRICK,
  BlockType.BOOKSHELF,
  BlockType.CHEST,
  BlockType.CRAFTING_TABLE,
  BlockType.FURNACE,
  BlockType.OBSIDIAN,
  BlockType.ICE,
  BlockType.PUMPKIN,
  BlockType.HAY_BALE,
  BlockType.CLAY,
  BlockType.TNT,
  BlockType.GLOWSTONE,
  BlockType.SNOW,
];

export const ItemType = {
  APPLE: 100,
  BREAD: 101,
};

export const FOOD_DATA = {
  [100]: { restore: 4 },
  [101]: { restore: 5 },
};

export function isBlock(type) { return type > 0 && type < 100; }
export function isFood(type)  { return type >= 100; }
